name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      path_to_dockerfile:
        description: Path to the Dockerfile
        default: "Dockerfile"
        type: string
      docker_build_dir:
        description: Docker build directory
        default: "."
        type: string
      image_tag:
        description: Tag for the image
        type: string
        default: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.AWS_REGION }}
        run: |
          echo "Configuring AWS CLI"
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          echo "Logging into ECR"
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

      - name: Build Docker Image
        id: build-image
        run: |
          echo "Building Docker Image"
          docker build "${{ inputs.docker_build_dir }}" -f "${{ inputs.path_to_dockerfile }}" -t "$ECR_REPOSITORY_URI:${{ inputs.image_tag }}"

      - name: Push Docker Image to ECR
        run: |
          echo "Pushing Docker Image"
          docker push "$ECR_REPOSITORY_URI:${{ inputs.image_tag }}"
