name: Build and Push Docker Image to ECR.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG .

      # Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG
